version: "3.3"
services:
  web:
    image: node:18
    ports:
      - "5173:5173"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    command: sh -c "cd /app; yarn install; yarn run dev --host 0.0.0.0"

    network_mode: "host"